# Generated by Django 3.2.13 on 2022-05-02 17:57

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220502_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(max_length=255, upload_to=recipes.models.Recipe.upload_to, verbose_name='Фотография'),
        ),
    ]
