# Generated by Django 3.2.13 on 2022-04-26 14:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=users.models.User.upload_to),
            preserve_default=False,
        ),
    ]
