# Generated by Django 3.2.13 on 2022-04-26 15:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default/user.png', upload_to=users.models.User.upload_to),
        ),
    ]
